sudo: required

os:
  - linux

language: go

services:
  - docker

go:
  - master

script:
  - docker --version
  - go test -v $(go list ./... | grep -v /vendor/) -cover
  - if [[ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]]; then
      pip install --user awscli;
      export PATH=$PATH:$HOME/.local/bin;
      aws --version;
      eval $(aws ecr get-login --region ap-northeast-1);
      if [[ $TRAVIS_TAG == *"dev"* ]]; then
        export PULLR_IMAGE_NAME=icariumdev:${TRAVIS_TAG};
      else
        export PULLR_IMAGE_NAME=icarium:${TRAVIS_TAG};
      fi;
      docker build -t ${PULLR_IMAGE_NAME} .;
      docker images;
      docker tag ${PULLR_IMAGE_NAME} ${ECR_REPO_URI}/${PULLR_IMAGE_NAME};
      docker push ${ECR_REPO_URI}/${PULLR_IMAGE_NAME};
    else
      go build -v;
    fi

notifications:
  slack:
    secure: OMdHmwlYTxFtCu5SQpxsvAaDODshF+iO8OxSXZUxIW5F2/r4UTM62ugNrzg12bMWklEVJF7SapAPVzhye/24aICboxifRe1Q7WaGyG3kvGUsGoZRopg02TaGQs/Mtq8sbtSpdCOVHWwFWWoSChr9nWVODJ6AN0eTtFeko5ZoK0XcdfXOn27cK6YaOjR3gBqMnkVMGwYCZNJQTPMp93zmbvAgo+ITJA5RZYBnjyNr2XqtHExoxbzvSp7LfkZqu+CQfp+FBrQ6a6PlEce+DiYzN0X+1sUuEBx/Xx9hsVvJLNMQZYPtvk0dKweR4O+GgZvDswFDaorovjco+yoOAZh6H1PlzlJZTL5M6ekoM/Mm0pGmFwQMp/HGzQsmVOswwtk8JMBy+pWIBikQKtT9F6ujxmWzz/s6fDscmzGEYygj8r6Qcn2HMHyULuq/orpmfd/HzHRHd3CHSy/sJAvK+6Sv8S0Ty8sbVD0b5WDbqOHiLE2OIfbN47I+w19bRx9YpwUYxJTDHGRS6qAKFc+QqqcKw+oW9ZSeFqNPAsVPpaGOXclYwz3rPxLUuaTb5SHCsMEw9erL+akzZOHfmVxVHFJ+ZFwzzRAVfl4Oqc/qCPXBU6CUIz6xXMenLhEtA1gbegAkYAlFZUdCKiwkdLsmyVMjRTX8ESfoWG4T6UTR4j5ioLg=
