version: 0.0
files:
  - source: /*
    destination: /home/ec2-user/go/src/github.com/mobingilabs/pullr-icarium
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
      runas: ec2-user
